{ 
    "_id" : "5434d85baa0cf8182800004e", 
    "formdata" : {
        "sections" : [
            {
                "type" : "section", 
                "visiblity" : true, 
                "class" : "", 
                "index" : NumberInt(7), 
                "sectionid" : "", 
                "sectiondataid" : "elbowright", 
                "sectionname" : "Elbow- Right"
            }
        ], 
        "forms" : {
            "elbowright" : [
                {
                    "id" : NumberInt(0), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(0), 
                    "label" : "Inspect", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblInspect", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(1), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(1), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No scars"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNoScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkInspectNoScars'] == 'No scars') { scope.report.data['objectivefindingselbowright']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingselbowright']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(2), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(2), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No swelling/effusion", 
                        "No erythema", 
                        "No deformity"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNo", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(3), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(3), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Surgical scars well healed"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectSurgical", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkInspectSurgical'] == 'Surgical scars well healed') { scope.report.data['objectivefindingselbowright']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingselbowright']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(4), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(4), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(5), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(5), 
                    "label" : "Palpation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPalpation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(6), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(6), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Non-tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationNonTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkPalpationNonTender'] == 'Non-tender' || scope.$parent.default.chkPalpationNonTender=='Non-tender') { \tscope.report.data['objectivefindingselbowright']['chkPalpationTender'] = []; scope.$parent.default.chkPalpationTender = []; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(7), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(7), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkPalpationTender'] == 'Tender') { \tscope.report.data['objectivefindingselbowright']['chkPalpationNonTender'] = []; scope.$parent.default.chkPalpationNonTender = []; } else { \tscope.report.data['objectivefindingselbowright']['chkPalpationTenderOptions'] = [];  \tscope.$parent.default.chkPalpationTenderOptions = [];  \tscope.report.data['objectivefindingselbowright']['chkPalpationTenderOtherTextarea'] = \"\";scope.$parent.default.chkPalpationTenderOtherTextarea=[];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(8), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(8), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Medial epicondyle", 
                        "Olecronon", 
                        "Lateral epicondyle", 
                        "Radial head", 
                        "Radial tunnel"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(9), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(9), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkPalpationTender'] != 'Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "margin-left-1"
                }, 
                {
                    "id" : NumberInt(10), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(10), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(11), 
                    "component" : "labelwithpopup", 
                    "editable" : true, 
                    "index" : NumberInt(11), 
                    "label" : "Elbow Ranges of Motion Figure Table A1 page 596, Corrected with Errata March 2002: AMA Estimated Normal: Flexion (150D), Extension (0D), Supination (80D), Pronation (80D).", 
                    "description" : "description", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lbl2", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "Hyper-extension is measured with a '+' preceeding the measurement. i.e. +10 = 10 degrees of hyper-extension.", 
                    "ispopup" : true, 
                    "checkboxclass" : "", 
                    "popuplable" : "(i)", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "ngchangecondition" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "rangefrom" : "", 
                    "rangeto" : "", 
                    "alertmessage" : ""
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "inputLabel", 
                    "editable" : false, 
                    "index" : NumberInt(58), 
                    "label" : "Actual goniometer measurements of the range of motion are only required for PR-4 (Permanent & Stationary) reports. Visual estimates of the range of motion may be adequate for Doctor's First reports and PR-2 reports.", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblCervicalMotionText", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "colorRed", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(12), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(12), 
                    "label" : "Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(13), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(13), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(14), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(14), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(15), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(15), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(16), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(16), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(17), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(17), 
                    "label" : "Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(18), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(18), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(19), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(19), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(20), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(20), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(21), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(21), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(22), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(22), 
                    "label" : "Supination", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblSupination", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(23), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(23), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtSupinationRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(24), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(24), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(25), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(25), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtSupinationLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(26), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(26), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(27), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(27), 
                    "label" : "Pronation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPronation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(28), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(28), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPronationRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(29), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(29), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(30), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(30), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPronationLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(31), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(31), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(32), 
                    "component" : "labelwithpopup", 
                    "editable" : true, 
                    "index" : NumberInt(32), 
                    "label" : "Manual Muscle Testing", 
                    "description" : "description", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblManualMuscleTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "Strength Definitions: 5=Complete active range of motion against gravity with full resistance, 4=Complete active range of motion against gravity with some resistance, 3=Complete active range of motion against gravity only, without resistance, 2=Complete active range of motion with gravity eliminated, 1=Evidence of slight contractility; no joint movement, 0=No evidence of contractility", 
                    "ispopup" : true, 
                    "checkboxclass" : "", 
                    "popuplable" : "(i)", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "ngchangecondition" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "rangefrom" : "", 
                    "rangeto" : "", 
                    "alertmessage" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(33), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(33), 
                    "label" : "5/5 strength all plane", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMuscleStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(34), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(34), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMuscleStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['rdoMuscleStrength'] == 'Yes') { \t  \tscope.report.data['objectivefindingselbowright']['chkMuscleStrengthFlexion'] = [];  \tscope.$parent.default.chkMuscleStrengthFlexion = []; scope.report.data['objectivefindingselbowright']['rdoFlexionPainful'] = [];  \tscope.$parent.default.rdoFlexionPainful = []; scope.report.data['objectivefindingselbowright']['ddlFlexionPainfulStrength'] = [];  \tscope.$parent.default.ddlFlexionPainfulStrength = [];  scope.report.data['objectivefindingselbowright']['chkMuscleStrengthExtension'] = [];  \tscope.$parent.default.chkMuscleStrengthExtension = []; scope.report.data['objectivefindingselbowright']['rdoExtensionPainful'] = [];  \tscope.$parent.default.rdoExtensionPainful = []; scope.report.data['objectivefindingselbowright']['ddlExtensionPainfulStrength'] = [];  \tscope.$parent.default.ddlExtensionPainfulStrength = []; scope.report.data['objectivefindingselbowright']['chkMuscleStrengthSupination'] = [];  \tscope.$parent.default.chkMuscleStrengthSupination = [];scope.report.data['objectivefindingselbowright']['rdoSupinationPainful'] = [];  \tscope.$parent.default.rdoSupinationPainful = []; scope.report.data['objectivefindingselbowright']['ddlSupinationPainfulStrength'] = [];  \tscope.$parent.default.ddlSupinationPainfulStrength = []; scope.report.data['objectivefindingselbowright']['chkMuscleStrengthPronation'] = [];  \tscope.$parent.default.chkMuscleStrengthPronation = [];scope.report.data['objectivefindingselbowright']['rdoPronationPainful'] = [];  \tscope.$parent.default.rdoPronationPainful = []; scope.report.data['objectivefindingselbowright']['ddlPronationPainfulStrength'] = [];  \tscope.$parent.default.ddlPronationPainfulStrength = []; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(35), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(35), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Flexion"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['rdoMuscleStrength']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkMuscleStrengthFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkMuscleStrengthFlexion'] != 'Flexion') { \t  \tscope.report.data['objectivefindingselbowright']['rdoFlexionPainful'] = [];  \tscope.$parent.default.rdoFlexionPainful = []; scope.report.data['objectivefindingselbowright']['ddlFlexionPainfulStrength'] = [];  \tscope.$parent.default.ddlFlexionPainfulStrength = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(36), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(36), 
                    "label" : "Painful upon testing", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthFlexion']!='Flexion'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoFlexionPainful", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(37), 
                    "component" : "select", 
                    "editable" : true, 
                    "index" : NumberInt(37), 
                    "label" : "Strength (0-4):", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "0", 
                        "1", 
                        "2", 
                        "3", 
                        "4"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 removePadding", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthFlexion']!='Flexion'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "ddlFlexionPainfulStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(38), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(38), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Extension"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['rdoMuscleStrength']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkMuscleStrengthExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkMuscleStrengthExtension'] != 'Extension') { scope.report.data['objectivefindingselbowright']['rdoExtensionPainful'] = [];  \tscope.$parent.default.rdoExtensionPainful = []; scope.report.data['objectivefindingselbowright']['ddlExtensionPainfulStrength'] = [];  \tscope.$parent.default.ddlExtensionPainfulStrength = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(39), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(39), 
                    "label" : "Painful upon testing", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthExtension']!='Extension'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoExtensionPainful", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(40), 
                    "component" : "select", 
                    "editable" : true, 
                    "index" : NumberInt(40), 
                    "label" : "Strength (0-4):", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "0", 
                        "1", 
                        "2", 
                        "3", 
                        "4"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 removePadding", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthExtension']!='Extension'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "ddlExtensionPainfulStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(41), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(41), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Supination"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['rdoMuscleStrength']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkMuscleStrengthSupination", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkMuscleStrengthSupination'] != 'Supination') {  scope.report.data['objectivefindingselbowright']['rdoSupinationPainful'] = [];  \tscope.$parent.default.rdoSupinationPainful = []; scope.report.data['objectivefindingselbowright']['ddlSupinationPainfulStrength'] = [];  \tscope.$parent.default.ddlSupinationPainfulStrength = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(42), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(42), 
                    "label" : "Painful upon testing", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthSupination']!='Supination'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoSupinationPainful", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(43), 
                    "component" : "select", 
                    "editable" : true, 
                    "index" : NumberInt(43), 
                    "label" : "Strength (0-4):", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "0", 
                        "1", 
                        "2", 
                        "3", 
                        "4"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 removePadding", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthSupination']!='Supination'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "ddlSupinationPainfulStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(44), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(44), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Pronation"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['rdoMuscleStrength']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkMuscleStrengthPronation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingselbowright']['chkMuscleStrengthPronation'] != 'Pronation') {  scope.report.data['objectivefindingselbowright']['rdoPronationPainful'] = [];  \tscope.$parent.default.rdoPronationPainful = []; scope.report.data['objectivefindingselbowright']['ddlPronationPainfulStrength'] = [];  \tscope.$parent.default.ddlPronationPainfulStrength = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(45), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(45), 
                    "label" : "Painful upon testing", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthPronation']!='Pronation'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoPronationPainful", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(46), 
                    "component" : "select", 
                    "editable" : true, 
                    "index" : NumberInt(46), 
                    "label" : "Strength (0-4):", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "0", 
                        "1", 
                        "2", 
                        "3", 
                        "4"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 removePadding", 
                    "condition" : "report.data['objectivefindingselbowright']['chkMuscleStrengthPronation']!='Pronation'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "ddlPronationPainfulStrength", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 margin-left-2"
                }, 
                {
                    "id" : NumberInt(47), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(47), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkMuscleStrengthOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(48), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(48), 
                    "label" : "Distal Neurovascular Exam", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblDistalNeurovascular", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(49), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(49), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Intact light touch", 
                        "Intact 5/5 Motor", 
                        "Intact Reflexes"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascular", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(50), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(50), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascularOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(51), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(51), 
                    "label" : "Tinel Test Ulnar Groove", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblTinelTest", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(52), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(52), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Negative", 
                        "Positive", 
                        "Not done"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTinelTest", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(53), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(53), 
                    "label" : "Free Data Entry", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFreeDataEntry", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(54), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(54), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "textareaFreeDataEntry", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }
            ], 
        }, 
        "data" : {
            "neck" : {

            }, 
            "midback" : {

            }, 
            "lowback" : {

            }, 
            "undefined" : {

            }, 
            "wristleft" : {

            }, 
            "neckleft" : [

            ], 
            "upperextremityleft" : {

            }, 
            "trunkleft" : {

            }, 
            "upperextremityright" : {

            }, 
            "trunkright" : {

            }, 
            "groingenitalialeft" : {

            }, 
            "cervical" : {

            }, 
            "thoracic" : {

            }, 
            "lumbar" : {

            }, 
            "neckright" : {

            }, 
            "trunk" : {

            }, 
            "groingenitaliaright" : {

            }, 
            "groingenitalia" : {

            }, 
            "skinother" : {

            }, 
            "skinotherleft" : {

            }, 
            "skinotherright" : {

            }, 
            "thumbright" : {

            }, 
            "upperextremityother" : {

            }, 
            "upperextremityotherleft" : {

            }, 
            "upperextremityotherright" : {

            }, 
            "lowerextremityother" : {

            }, 
            "lowerextremityotherleft" : {

            }, 
            "lowerextremityotherright" : {

            }, 
            "other" : {

            }, 
            "otherleft" : {

            }, 
            "otherright" : {

            }, 
            "shoulderleft" : {

            }, 
            "elbowleft" : {

            }, 
            "lowerextremityright" : {

            }, 
            "lowerextremityleft" : {

            }, 
            "kneeright" : {

            }, 
            "toeright" : {

            }, 
            "pelvishipright" : {

            }, 
            "kneeleft" : {

            }, 
            "toeleft" : {

            }
        }
    }, 
    "formname" : "PR-2 Objective Findings Thoracic Version 1", 
    "status" : "draft", 
    "type" : "template", 
    "formtype" : "pr2"
}