{ 
    "_id" : "5434d85baa0cf8182800004e", 
    "formdata" : {
        "sections" : [
             {
                "type" : "section", 
                "visiblity" : true, 
                "class" : "", 
                "index" : NumberInt(12), 
                "sectionid" : "", 
                "sectiondataid" : "fingerindexright", 
                "sectionname" : "Finger - Index - Right"
            }
        ], 
        "forms" : {
            "fingerindexright" : [
                {
                    "id" : NumberInt(0), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(0), 
                    "label" : "Inspect", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblInspect", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(1), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(1), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No scars"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNoScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingsfingerindexright']['chkInspectNoScars'] == 'No scars') { scope.report.data['objectivefindingsfingerindexright']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingsfingerindexright']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(2), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(2), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No swelling/effusion", 
                        "No erythema", 
                        "No deformity"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNo", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(3), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(3), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Surgical scars well healed"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectSurgical", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingsfingerindexright']['chkInspectSurgical'] == 'Surgical scars well healed') { scope.report.data['objectivefindingsfingerindexright']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingsfingerindexright']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(4), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(4), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(5), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(5), 
                    "label" : "Palpation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPalpation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(6), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(6), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Non-tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationNonTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingsfingerindexright']['chkPalpationNonTender'] == 'Non-tender' || scope.$parent.default.chkPalpationNonTender=='Non-tender') { \tscope.report.data['objectivefindingsfingerindexright']['chkPalpationTender'] = []; scope.$parent.default.chkPalpationTender = []; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(7), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(7), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingsfingerindexright']['chkPalpationTender'] == 'Tender') { \tscope.report.data['objectivefindingsfingerindexright']['chkPalpationNonTender'] = []; scope.$parent.default.chkPalpationNonTender = []; } else { \tscope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderOptions'] = [];  \tscope.$parent.default.chkPalpationTenderOptions = []; scope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderPhalanx'] = [];  \tscope.$parent.default.chkPalpationTenderPhalanx = []; scope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderMetacarpal'] = [];  \tscope.$parent.default.chkPalpationTenderMetacarpal = [];\tscope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderOther'] = [];  \tscope.$parent.default.chkPalpationTenderOther = []; \tscope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderOtherTextarea'] = \"\";}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(8), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(8), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Metacarpal"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(9), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(9), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Phalanx"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderPhalanx", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderPhalanx'] != 'Phalanx') { \tscope.report.data  ['objectivefindingsfingerindexright']['chkPalpationTenderPhalanxOptions'] = [];  \tscope.  $parent.default.chkPalpationTenderPhalanxOptions = []; scope.report.data['objectivefindingsfingerindexright']  ['chkPalpationTenderPhalanxOther'] = [];  \tscope.$parent.default.chkPalpationTenderPhalanxOther = []; \t  scope.report.data['objectivefindingsfingerindexright']['chkPalpationTenderPhalanxOtherTextarea'] = \"\"; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(10), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(10), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Proximal", 
                        "Middle", 
                        "Distal"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['chkPalpationTenderPhalanx']!='Phalanx'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderPhalanxOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(11), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(11), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['chkPalpationTenderPhalanx']!='Phalanx'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderPhalanxOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(12), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(12), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Metacarpal phalangeal (MP) joint", 
                        "Interphalangeal (IP) joint", 
                        "Distal interphalangeal (DIP) joint"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderMetacarpal", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(13), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(13), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(14), 
                    "component" : "labelwithpopup", 
                    "editable" : true, 
                    "index" : NumberInt(14), 
                    "label" : "Finger Ranges of Motion Figures 16-21 page 461, 16-23 page 463, 16-25 page 464: AMA Estimated Normal: DIP Flexion (70D) DIP Extension (0D), PIP Flexion (100D) PIP Extension (0D), MP Flexion (90D) MP Extension (+20D).", 
                    "description" : "description", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblThumbRanges", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "Hyper-extension is measured with a '+' preceeding the measurement. i.e. +10 = 10 degrees of hyper-extension.", 
                    "ispopup" : true, 
                    "checkboxclass" : "", 
                    "popuplable" : "(i)", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "inputLabel", 
                    "editable" : false, 
                    "index" : NumberInt(58), 
                    "label" : "Actual goniometer measurements of the range of motion are only required for PR-4 (Permanent & Stationary) reports. Visual estimates of the range of motion may be adequate for Doctor's First reports and PR-2 reports.", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblCervicalMotionText", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "colorRed", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(15), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(15), 
                    "label" : "DIP Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblDIPFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(16), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(16), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtDIPFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(17), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(17), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(18), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(18), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtDIPFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(19), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(19), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(20), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(20), 
                    "label" : "DIP Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblDIPExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(21), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(21), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtDIPExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(22), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(22), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(23), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(23), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtDIPExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(24), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(24), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(25), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(25), 
                    "label" : "PIP Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPIPFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(26), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(26), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPIPFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(27), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(27), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(28), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(28), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPIPFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(29), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(29), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(30), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(30), 
                    "label" : "PIP Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPIPExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(31), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(31), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPIPExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(32), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(32), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(33), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(33), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtPIPExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(34), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(34), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(35), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(35), 
                    "label" : "MP Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMPFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(36), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(36), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtMPFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(37), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(37), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(38), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(38), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtMPFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(39), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(39), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(40), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(40), 
                    "label" : "MP Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMPExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(41), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(41), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtMPExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(42), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(42), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(43), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(43), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtMPExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(44), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(44), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "jsdf", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "ngchangecondition" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "rangefrom" : "", 
                    "rangeto" : "", 
                    "alertmessage" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(45), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(45), 
                    "label" : "Neurovascular Exam", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "cvx", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(46), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(46), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Grip 5/5 Motor", 
                        "Pinch 5/5 Motor"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkNeurovascularOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(47), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(47), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkNeurovascularOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(48), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(48), 
                    "label" : "Light Touch Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(49), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(49), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(50), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(50), 
                    "label" : "Mono Filament Testing Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(51), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(51), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(52), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(52), 
                    "label" : "Gram weight of Monofilament", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(53), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(53), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "3", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(54), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(54), 
                    "label" : "Two Point Testing (6 mm) Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(55), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(55), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingsfingerindexright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "select", 
                    "editable" : true, 
                    "index" : NumberInt(58), 
                    "label" : "Triggering", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "None", 
                        "Mild - Inconsistent triggering during active range of motion", 
                        "Moderate - Constant triggering during active range of motion", 
                        "Severe-Constant triggering during passive range of motion"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "triggeringdropdown", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "displaycalculation" : "", 
                    "ngchangecondition" : "", 
                    "rangefrom" : "", 
                    "rangeto" : "", 
                    "alertmessage" : ""
                }, 
                {
                    "id" : NumberInt(59), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(59), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "triggeringOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }
            ]
        }, 
        "data" : {
            "neck" : {

            }, 
            "midback" : {

            }, 
            "lowback" : {

            }, 
            "undefined" : {

            }, 
            "wristleft" : {

            }, 
            "neckleft" : [

            ], 
            "upperextremityleft" : {

            }, 
            "trunkleft" : {

            }, 
            "upperextremityright" : {

            }, 
            "trunkright" : {

            }, 
            "groingenitalialeft" : {

            }, 
            "cervical" : {

            }, 
            "thoracic" : {

            }, 
            "lumbar" : {

            }, 
            "neckright" : {

            }, 
            "trunk" : {

            }, 
            "groingenitaliaright" : {

            }, 
            "groingenitalia" : {

            }, 
            "skinother" : {

            }, 
            "skinotherleft" : {

            }, 
            "skinotherright" : {

            }, 
            "thumbright" : {

            }, 
            "upperextremityother" : {

            }, 
            "upperextremityotherleft" : {

            }, 
            "upperextremityotherright" : {

            }, 
            "lowerextremityother" : {

            }, 
            "lowerextremityotherleft" : {

            }, 
            "lowerextremityotherright" : {

            }, 
            "other" : {

            }, 
            "otherleft" : {

            }, 
            "otherright" : {

            }, 
            "shoulderleft" : {

            }, 
            "elbowleft" : {

            }, 
            "lowerextremityright" : {

            }, 
            "lowerextremityleft" : {

            }, 
            "kneeright" : {

            }, 
            "toeright" : {

            }, 
            "pelvishipright" : {

            }, 
            "kneeleft" : {

            }, 
            "toeleft" : {

            }
        }
    }, 
    "formname" : "PR-2 Objective Findings Thoracic Version 1", 
    "status" : "draft", 
    "type" : "template", 
    "formtype" : "pr2"
}