{ 
    "_id" : "5434d85baa0cf8182800004e", 
    "formdata" : {
        "sections" : [
             {
                "type" : "section", 
                "visiblity" : true, 
                "class" : "", 
                "index" : NumberInt(21), 
                "sectionid" : "", 
                "sectiondataid" : "kneeleft", 
                "sectionname" : "Knee - Left"
            }
        ], 
        "forms" : {
            "kneeleft" : [
                {
                    "id" : NumberInt(0), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(0), 
                    "label" : "Inspect", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblInspect", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(1), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(1), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No scars"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNoScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingskneeleft']['chkInspectNoScars'] == 'No scars') { scope.report.data['objectivefindingskneeleft']['chkInspectSurgicalScars'] = []; scope.$parent.default.chkInspectSurgicalScars = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(2), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(2), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No erythema", 
                        "No swelling/effusion", 
                        "No deformity"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNo", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(3), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(3), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Surgical scars/scars healed"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectSurgicalScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingskneeleft']['chkInspectSurgicalScars'] == 'Surgical scars/scars healed') { scope.report.data['objectivefindingskneeleft']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(4), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(4), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(5), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(5), 
                    "label" : "Palpation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPalpation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(6), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(6), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Non-tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationNonTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingskneeleft']['chkPalpationNonTender'] == 'Non-tender' || scope.$parent.default.chkPalpationNonTender=='Non-tender') { \tscope.report.data['objectivefindingskneeleft']['chkPalpationTender'] = []; scope.$parent.default.chkPalpationTender = []; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(7), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(7), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingskneeleft']['chkPalpationTender'] == 'Tender') { \tscope.report.data['objectivefindingskneeleft']['chkPalpationNonTender'] = []; scope.$parent.default.chkPalpationNonTender = []; } else { \tscope.report.data['objectivefindingskneeleft']['chkPalpationTenderOptions'] = [];  \tscope.$parent.default.chkPalpationTenderOptions = []; \tscope.report.data['objectivefindingskneeleft']['chkPalpationTenderOther'] = [];  \tscope.$parent.default.chkPalpationTenderOther = []; \tscope.report.data['objectivefindingskneeleft']['chkPalpationTenderOtherTextarea'] = \"\"; \t\t }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(8), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(8), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Anterior", 
                        "Medial", 
                        "Lateral", 
                        "Posterior"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingskneeleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(9), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(9), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingskneeleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch", 
                    "mainclass" : "margin-left-1"
                }, 
                {
                    "id" : NumberInt(10), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(10), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(11), 
                    "component" : "labelwithpopup", 
                    "editable" : true, 
                    "index" : NumberInt(11), 
                    "label" : "Knee Ranges of Motion Table A-3 page 598: AMA Estimated Normal: Flexion (150D), Extension (0D).", 
                    "description" : "description", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblKneeRanges", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "Hyper-extension is measured with a '+' preceeding the measurement. i.e. +10 = 10 degrees of hyper-extension.", 
                    "ispopup" : true, 
                    "checkboxclass" : "", 
                    "popuplable" : "(i)", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "inputLabel", 
                    "editable" : false, 
                    "index" : NumberInt(58), 
                    "label" : "Actual goniometer measurements of the range of motion are only required for PR-4 (Permanent & Stationary) reports. Visual estimates of the range of motion may be adequate for Doctor's First reports and PR-2 reports.", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblCervicalMotionText", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "colorRed", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(12), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(12), 
                    "label" : "Valgus Deformity (degrees) Right", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "2", 
                    "validation" : "/.*/", 
                    "uniqueid" : "valgusDeformityDegRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-5 removePadding clearer", 
                    "rangefrom" : "0", 
                    "rangeto" : "99"
                }, 
                {
                    "id" : NumberInt(13), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(13), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sdf", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-1 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : ""
                }, 
                {
                    "id" : NumberInt(14), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(14), 
                    "label" : "Valgus Deformity (degrees) Left", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "2", 
                    "validation" : "/.*/", 
                    "uniqueid" : "valgusDeformityDegLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-5 removePadding clearer", 
                    "rangefrom" : "0", 
                    "rangeto" : "99"
                }, 
                {
                    "id" : NumberInt(15), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(15), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sdf", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-1 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "displaycalculation" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : ""
                }, 
                {
                    "id" : NumberInt(16), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(16), 
                    "label" : "Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(17), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(17), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-5 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(18), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(18), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(19), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(19), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(20), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(20), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(21), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(21), 
                    "label" : "Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(22), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(22), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-5 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(23), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(23), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(24), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(24), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(25), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(25), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(26), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(26), 
                    "label" : "Ligament Testing", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblLigamentTest", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(27), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(27), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Stable on Comparison", 
                        "Unstable"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLigamentTest", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(28), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(28), 
                    "label" : "Posterior Cruciate Ligament", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Stable", 
                        "Mild", 
                        "Moderate", 
                        "Severe"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLigamentTest']!='Unstable'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoPosteriorLigament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-4", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(29), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(29), 
                    "label" : "Anterior Cruciate Ligament", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Stable", 
                        "Mild", 
                        "Moderate", 
                        "Severe"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLigamentTest']!='Unstable'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoAnteriorLigament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-4", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(30), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(30), 
                    "label" : "Lateral Collateral Ligament", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Stable", 
                        "Mild", 
                        "Moderate", 
                        "Severe"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLigamentTest']!='Unstable'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLateralLigament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-4", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(31), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(31), 
                    "label" : "Medial Collateral Ligament", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Stable", 
                        "Mild", 
                        "Moderate", 
                        "Severe"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLigamentTest']!='Unstable'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMedialLigament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-4", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : ""
                }, 
                {
                    "id" : NumberInt(32), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(32), 
                    "label" : "Special Testing: McMurray's Test", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblSpecialTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(33), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(33), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Negative", 
                        "Positive"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoSpecialTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingskneeleft']['rdoSpecialTesting']=='Negative'){scope.report.data['objectivefindingskneeleft']['chkSpecialTestingOptions']=[]; scope.$parent.default.chkSpecialTestingOptions=[];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(34), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(34), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Medial joint", 
                        "Lateral joint"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoSpecialTesting']!='Positive'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkSpecialTestingOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(35), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(35), 
                    "label" : "Free Data Entry", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "textareaSpecialTestingFreeDataEntry", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(36), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(36), 
                    "label" : "Distal Neurovascular Exam", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblDistalNeurovascular", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(37), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(37), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Intact motor 5/5", 
                        "Intact Reflexes"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascularOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(38), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(38), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascularOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(39), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(39), 
                    "label" : "Light Touch Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblLightTouch", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(40), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(40), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLightTouch", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "displaycalculation" : "", 
                    "ngchangecondition" : "", 
                    "rangefrom" : "", 
                    "rangeto" : "", 
                    "alertmessage" : ""
                }, 
                {
                    "id" : NumberInt(41), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(41), 
                    "label" : "Mono Filament Testing Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(42), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(42), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(43), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(43), 
                    "label" : "Gram weight of Monofilament", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblGramWeight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(44), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(44), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 margin-left-1", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "3", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtGramWeight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(45), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(45), 
                    "label" : "Two Point Testing (6 mm) Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblTwoPoint", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(46), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(46), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingskneeleft']['rdoLightTouch']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTwoPoint", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }
            ]
        }, 
        "data" : {
            "neck" : {

            }, 
            "midback" : {

            }, 
            "lowback" : {

            }, 
            "undefined" : {

            }, 
            "wristleft" : {

            }, 
            "neckleft" : [

            ], 
            "upperextremityleft" : {

            }, 
            "trunkleft" : {

            }, 
            "upperextremityright" : {

            }, 
            "trunkright" : {

            }, 
            "groingenitalialeft" : {

            }, 
            "cervical" : {

            }, 
            "thoracic" : {

            }, 
            "lumbar" : {

            }, 
            "neckright" : {

            }, 
            "trunk" : {

            }, 
            "groingenitaliaright" : {

            }, 
            "groingenitalia" : {

            }, 
            "skinother" : {

            }, 
            "skinotherleft" : {

            }, 
            "skinotherright" : {

            }, 
            "thumbright" : {

            }, 
            "upperextremityother" : {

            }, 
            "upperextremityotherleft" : {

            }, 
            "upperextremityotherright" : {

            }, 
            "lowerextremityother" : {

            }, 
            "lowerextremityotherleft" : {

            }, 
            "lowerextremityotherright" : {

            }, 
            "other" : {

            }, 
            "otherleft" : {

            }, 
            "otherright" : {

            }, 
            "shoulderleft" : {

            }, 
            "elbowleft" : {

            }, 
            "lowerextremityright" : {

            }, 
            "lowerextremityleft" : {

            }, 
            "kneeright" : {

            }, 
            "toeright" : {

            }, 
            "pelvishipright" : {

            }, 
            "kneeleft" : {

            }, 
            "toeleft" : {

            }
        }
    }, 
    "formname" : "PR-2 Objective Findings Thoracic Version 1", 
    "status" : "draft", 
    "type" : "template", 
    "formtype" : "pr2"
}