{ 
    "_id" : "5434d85baa0cf8182800004e", 
    "formdata" : {
        "sections" : [
             {
                "type" : "section", 
                "visiblity" : true, 
                "class" : "", 
                "index" : NumberInt(26), 
                "sectionid" : "", 
                "sectiondataid" : "toeright", 
                "sectionname" : "Toe(s) - Right"
            }
        ], 
        "forms" : {
            "toeright" : [
                {
                    "id" : NumberInt(0), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(0), 
                    "label" : "Inspect", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblInspect", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(1), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(1), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No scars"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNoScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingstoeright']['chkInspectNoScars'] == 'No scars') { scope.report.data['objectivefindingstoeright']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(2), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(2), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No swelling", 
                        "No erythema", 
                        "No deformity"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNo", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(3), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(3), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Surgical scars/scars healed"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectSurgical", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingstoeright']['chkInspectSurgical'] == 'Surgical scars/scars healed') { scope.report.data['objectivefindingstoeright']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(4), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(4), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(5), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(5), 
                    "label" : "Palpation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPalpation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(6), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(6), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Non-tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationNonTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingstoeright']['chkPalpationNonTender'] == 'Non-tender') { scope.report.data['objectivefindingstoeright']['chkPalpationTender'] = []; scope.$parent.default.chkPalpationTender = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(7), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(7), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingstoeright']['chkPalpationTender'] == 'Tender') { scope.report.data['objectivefindingstoeright']['chkPalpationNonTender'] = []; scope.$parent.default.chkPalpationNonTender = [];}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(8), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(8), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(9), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(9), 
                    "label" : "Range of Motion: Note: Examined with knee at 45 degrees flexion and ankle 90 degrees (see page 536).", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblThumbRanges", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "inputLabel", 
                    "editable" : false, 
                    "index" : NumberInt(58), 
                    "label" : "Actual goniometer measurements of the range of motion are only required for PR-4 (Permanent & Stationary) reports. Visual estimates of the range of motion may be adequate for Doctor's First reports and PR-2 reports.", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblCervicalMotionText", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "colorRed", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(10), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(10), 
                    "label" : "Metatarsal Phalangeal Joint Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(11), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(11), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(12), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(12), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(13), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(13), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(14), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(14), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(15), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(15), 
                    "label" : "Metatarsal Phalangeal Joint Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(16), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(16), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(17), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(17), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(18), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(18), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(19), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(19), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sd", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(20), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(20), 
                    "label" : "Interphalangeal Joint Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "labelinterphalengeal", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-12 removePadding clearer"
                }, 
                {
                    "id" : NumberInt(21), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(21), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtInterphalangealRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(22), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(22), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "fdgdfgfdg", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(23), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(23), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtInterphalangealLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(24), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(24), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "sdfsdf", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "ispopup" : "", 
                    "checkboxclass" : "", 
                    "popuplable" : "", 
                    "uimasking" : "", 
                    "futuredate" : "", 
                    "validatoruniqueid" : "", 
                    "numberonly" : "", 
                    "numbercharonly" : "", 
                    "charonly" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(25), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(25), 
                    "label" : "Neurovascular Exam", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "cvx", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(26), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(26), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Extension 5/5 Motor", 
                        "Flexion 5/5 Motor"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkNeurovascularOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(27), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(27), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkNeurovascularOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(28), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(28), 
                    "label" : "Light Touch Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(29), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(29), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(30), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(30), 
                    "label" : "Mono Filament Testing Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(31), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(31), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(32), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(32), 
                    "label" : "Gram weight of Monofilament", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(33), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(33), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 margin-left-1", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "3", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(34), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(34), 
                    "label" : "Two Point Testing (6 mm) Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(35), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(35), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingstoeright']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }
            ]
        }, 
        "data" : {
            "neck" : {

            }, 
            "midback" : {

            }, 
            "lowback" : {

            }, 
            "undefined" : {

            }, 
            "wristleft" : {

            }, 
            "neckleft" : [

            ], 
            "upperextremityleft" : {

            }, 
            "trunkleft" : {

            }, 
            "upperextremityright" : {

            }, 
            "trunkright" : {

            }, 
            "groingenitalialeft" : {

            }, 
            "cervical" : {

            }, 
            "thoracic" : {

            }, 
            "lumbar" : {

            }, 
            "neckright" : {

            }, 
            "trunk" : {

            }, 
            "groingenitaliaright" : {

            }, 
            "groingenitalia" : {

            }, 
            "skinother" : {

            }, 
            "skinotherleft" : {

            }, 
            "skinotherright" : {

            }, 
            "thumbright" : {

            }, 
            "upperextremityother" : {

            }, 
            "upperextremityotherleft" : {

            }, 
            "upperextremityotherright" : {

            }, 
            "lowerextremityother" : {

            }, 
            "lowerextremityotherleft" : {

            }, 
            "lowerextremityotherright" : {

            }, 
            "other" : {

            }, 
            "otherleft" : {

            }, 
            "otherright" : {

            }, 
            "shoulderleft" : {

            }, 
            "elbowleft" : {

            }, 
            "lowerextremityright" : {

            }, 
            "lowerextremityleft" : {

            }, 
            "kneeright" : {

            }, 
            "toeright" : {

            }, 
            "pelvishipright" : {

            }, 
            "kneeleft" : {

            }, 
            "toeleft" : {

            }
        }
    }, 
    "formname" : "PR-2 Objective Findings Thoracic Version 1", 
    "status" : "draft", 
    "type" : "template", 
    "formtype" : "pr2"
}