{ 
    "_id" : "5434d85baa0cf8182800004e", 
    "formdata" : {
        "sections" : [
            {
                "type" : "section", 
                "visiblity" : true, 
                "class" : "", 
                "index" : NumberInt(8), 
                "sectionid" : "", 
                "sectiondataid" : "wristleft", 
                "sectionname" : "Wrist- Left"
            }
        ], 
        "forms" : {
            "wristleft" : [
                {
                    "id" : NumberInt(0), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(0), 
                    "label" : "Inspect", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblInspect", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(1), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(1), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No scars"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNoScars", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkInspectNoScars'] == 'No scars') { scope.report.data['objectivefindingswristleft']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingswristleft']['chkInspectSurgical'] = []; scope.$parent.default.chkInspectSurgical = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(2), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(2), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "No swelling/effusion", 
                        "No erythema", 
                        "No deformity"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectNo", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(3), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(3), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Surgical scars healed"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectSurgical", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkInspectSurgical'] == 'Surgical scars healed') { scope.report.data['objectivefindingswristleft']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];}", 
                    "watchvalidatorset" : "scope.report.data['objectivefindingswristleft']['chkInspectNoScars'] = []; scope.$parent.default.chkInspectNoScars = [];", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(4), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(4), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkInspectOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(5), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(5), 
                    "label" : "Palpation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblPalpation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(6), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(6), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Non-tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationNonTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkPalpationNonTender'] == 'Non-tender' || scope.$parent.default.chkPalpationNonTender=='Non-tender') { \tscope.report.data['objectivefindingswristleft']['chkPalpationTender'] = []; scope.$parent.default.chkPalpationTender = []; }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(7), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(7), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Tender"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTender", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkPalpationTender'] == 'Tender') { \tscope.report.data['objectivefindingswristleft']['chkPalpationNonTender'] = []; scope.$parent.default.chkPalpationNonTender = []; } else { \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderOptions'] = [];  \tscope.$parent.default.chkPalpationTenderOptions = []; scope.report.data['objectivefindingswristleft']['chkPalpationTenderOther'] = [];  \tscope.$parent.default.chkPalpationTenderOther = [];  scope.report.data['objectivefindingswristleft']['chkPalpationTenderCarpals'] = [];  \tscope.$parent.default.chkPalpationTenderCarpals = []; scope.report.data['objectivefindingswristleft']['chkPalpationTenderCarpalsOther'] = [];  \tscope.$parent.default.chkPalpationTenderCarpalsOther = []; scope.report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpals'] = [];  \tscope.$parent.default.chkPalpationTenderMetacarpals = []; scope.report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpalsOther'] = [];  \tscope.$parent.default.chkPalpationTenderMetacarpalsOther = [];  \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderOtherTextarea'] = \"\"; \t\t }", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(8), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(8), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Ulnar styloid", 
                        "Volar wrist/carpal tunnel", 
                        "Radial styloid", 
                        "1st dorsal compartment"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(9), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(9), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Carpals"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderCarpals", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkPalpationTenderCarpals'] != 'Carpals') { \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderCarpalsOptions'] = [];  \tscope.$parent.default.chkPalpationTenderCarpalsOptions = []; \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderCarpalsOtherTextarea'] = \"\";}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(10), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(10), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Navicular", 
                        "Trapezium", 
                        "Capitate", 
                        "Lunate", 
                        "Triquetrium", 
                        "Pisiform", 
                        "Hamate (Hook)"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTenderCarpals']!='Carpals'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderCarpalsOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(11), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(11), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTenderCarpals']!='Carpals'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderCarpalsOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "margin-left-2"
                }, 
                {
                    "id" : NumberInt(12), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(12), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Metacarpals"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderMetacarpals", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "if(scope.report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpals'] != 'Metacarpals') { \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpalsOptions'] = [];  \tscope.$parent.default.chkPalpationTenderMetacarpalsOptions = []; \tscope.report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpalsOtherTextarea'] = \"\";}", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : "onwatch", 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "validationevents" : "falseonwatch"
                }, 
                {
                    "id" : NumberInt(13), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(13), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "First (Thumb)", 
                        "Second (Index)", 
                        "Third (Middle)", 
                        "Fourth (Ring)", 
                        "Fifth (Little)"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpals']!='Metacarpals'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderMetacarpalsOptions", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(14), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(14), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-2", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTenderMetacarpals']!='Metacarpals'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderMetacarpalsOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "margin-left-2"
                }, 
                {
                    "id" : NumberInt(15), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(15), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['chkPalpationTender']!='Tender'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationTenderOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "margin-left-1"
                }, 
                {
                    "id" : NumberInt(16), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(16), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkPalpationOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(17), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(17), 
                    "label" : "Wrist Ranges of Motion Figure Table A1 page 596, Corrected with Errata March 2002: AMA Estimated Normal: Flexion (60D), Extension (60D), Ulnar Deviation (30D), Radial Deviation (20D).", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblShoulderRanges", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-12 removePadding"
                }, 
                {
                    "id" : NumberInt(58), 
                    "component" : "inputLabel", 
                    "editable" : false, 
                    "index" : NumberInt(58), 
                    "label" : "Actual goniometer measurements of the range of motion are only required for PR-4 (Permanent & Stationary) reports. Visual estimates of the range of motion may be adequate for Doctor's First reports and PR-2 reports.", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblCervicalMotionText", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "colorRed", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-10 removePadding"
                }, 
                {
                    "id" : NumberInt(18), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(18), 
                    "label" : "Flexion", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFlexion", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(19), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(19), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(20), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(20), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(21), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(21), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtFlexionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(22), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(22), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(23), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(23), 
                    "label" : "Extension", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblExtension", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(24), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(24), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(25), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(25), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(26), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(26), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtExtensionLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(27), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(27), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(28), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(28), 
                    "label" : "Ulnar Deviation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblUlnarDeviation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(29), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(29), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtUlnarDeviationRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(30), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(30), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(31), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(31), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtUlnarDeviationLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(32), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(32), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(33), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(33), 
                    "label" : "Radial Deviation", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblRadialDeviation", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "clearer"
                }, 
                {
                    "id" : NumberInt(34), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(34), 
                    "label" : "Right Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtRadialDeviationRight", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding clearer", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(35), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(35), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "hff", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-2 removePadding top-buffer", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(36), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(36), 
                    "label" : "Left Side", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-6 removePadding", 
                    "condition" : "", 
                    "maxlength" : "4", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtRadialDeviationLeft", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-5 removePadding", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-3 removePadding", 
                    "rangefrom" : "-360", 
                    "rangeto" : "360"
                }, 
                {
                    "id" : NumberInt(37), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(37), 
                    "label" : "D", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "kjfskdfhs", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : "", 
                    "mainclass" : "col-sm-2 removePadding top-buffer"
                }, 
                {
                    "id" : NumberInt(38), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(38), 
                    "label" : "Tinel Test Median Nerve", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Negative", 
                        "Positive", 
                        "Not Done"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTinelTest", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-3", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(39), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(39), 
                    "label" : "DeQuervain's", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Negative", 
                        "Positive", 
                        "Not Done"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoDeQuervains", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "col-sm-3", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(40), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(40), 
                    "label" : "Free Data Entry", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblFreeDataEntry", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(41), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(41), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "textareaFreeDataEntry", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(42), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(42), 
                    "label" : "Distal Neurovascular Exam", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblDistalNeurovascular", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(43), 
                    "component" : "checkbox", 
                    "editable" : true, 
                    "index" : NumberInt(43), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Grip 5/5 Motor", 
                        "Pinch 5/5 Motor"
                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascular", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(71), 
                    "component" : "TextEditorButton", 
                    "editable" : true, 
                    "index" : NumberInt(71), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "chkDistalNeurovascularOtherTextarea", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(44), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(44), 
                    "label" : "Light Touch Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(45), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(45), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "", 
                    "condition" : "", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoLightTouchIntact", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(46), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(46), 
                    "label" : "Mono Filament Testing Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(47), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(47), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoMonoFilament", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(48), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(48), 
                    "label" : "Gram weight of Monofilament", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(49), 
                    "component" : "textInputforonlynumbers", 
                    "editable" : true, 
                    "index" : NumberInt(49), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "col-sm-2 margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "3", 
                    "validation" : "/.*/", 
                    "uniqueid" : "txtGram", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(50), 
                    "component" : "inputLabel", 
                    "editable" : true, 
                    "index" : NumberInt(50), 
                    "label" : "Two Point Testing (6 mm) Intact", 
                    "description" : "", 
                    "placeholder" : "", 
                    "options" : [

                    ], 
                    "required" : false, 
                    "inline" : false, 
                    "inputclass" : "", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "lblTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "margin-left-1", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }, 
                {
                    "id" : NumberInt(51), 
                    "component" : "radio", 
                    "editable" : true, 
                    "index" : NumberInt(51), 
                    "label" : "", 
                    "description" : "", 
                    "placeholder" : "placeholder", 
                    "options" : [
                        "Yes", 
                        "No"
                    ], 
                    "required" : false, 
                    "inline" : true, 
                    "inputclass" : "margin-left-1", 
                    "condition" : "report.data['objectivefindingswristleft']['rdoLightTouchIntact']!='No'", 
                    "maxlength" : "", 
                    "validation" : "/.*/", 
                    "uniqueid" : "rdoTwoPointTesting", 
                    "disablecondition" : "", 
                    "validatorcondition" : "", 
                    "validatorset" : "", 
                    "blurvalidatorcondition" : "", 
                    "blurvalidatorset" : "", 
                    "watchvalidatorcondition" : "", 
                    "watchvalidatorset" : "", 
                    "isblur" : false, 
                    "iswatch" : false, 
                    "labelclass" : "", 
                    "onkeypress" : "", 
                    "textareatext" : ""
                }
            ]
        }, 
        "data" : {
            "neck" : {

            }, 
            "midback" : {

            }, 
            "lowback" : {

            }, 
            "undefined" : {

            }, 
            "wristleft" : {

            }, 
            "neckleft" : [

            ], 
            "upperextremityleft" : {

            }, 
            "trunkleft" : {

            }, 
            "upperextremityright" : {

            }, 
            "trunkright" : {

            }, 
            "groingenitalialeft" : {

            }, 
            "cervical" : {

            }, 
            "thoracic" : {

            }, 
            "lumbar" : {

            }, 
            "neckright" : {

            }, 
            "trunk" : {

            }, 
            "groingenitaliaright" : {

            }, 
            "groingenitalia" : {

            }, 
            "skinother" : {

            }, 
            "skinotherleft" : {

            }, 
            "skinotherright" : {

            }, 
            "thumbright" : {

            }, 
            "upperextremityother" : {

            }, 
            "upperextremityotherleft" : {

            }, 
            "upperextremityotherright" : {

            }, 
            "lowerextremityother" : {

            }, 
            "lowerextremityotherleft" : {

            }, 
            "lowerextremityotherright" : {

            }, 
            "other" : {

            }, 
            "otherleft" : {

            }, 
            "otherright" : {

            }, 
            "shoulderleft" : {

            }, 
            "elbowleft" : {

            }, 
            "lowerextremityright" : {

            }, 
            "lowerextremityleft" : {

            }, 
            "kneeright" : {

            }, 
            "toeright" : {

            }, 
            "pelvishipright" : {

            }, 
            "kneeleft" : {

            }, 
            "toeleft" : {

            }
        }
    }, 
    "formname" : "PR-2 Objective Findings Thoracic Version 1", 
    "status" : "draft", 
    "type" : "template", 
    "formtype" : "pr2"
}